name: FastMachines
version: '${project.version}'
main: net.guizhanss.fastmachines.FastMachines
api-version: 1.16
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
  - SlimefunTranslation
  - InfinityExpansion
  - SlimeFrame
authors: [ ybw0014 ]
description: A Slimefun Addon that adds better basic machines.
