name: Blob Build (Experimental)

on:
  push:
    branches:
      - experimental

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Rename jar file
        run: mv build/libs/FastMachines-*.jar build/libs/FastMachines.jar

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        if: github.ref == 'refs/heads/experimental'
        with:
          project: FastMachines
          releaseChannel: Experimental
          file: ./build/libs/FastMachines.jar
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
